let express = require('express')
let app = express()
let authRoutes = require('./routes/authroute')
let indexRoutes = require('./routes/indexRoutes')
let profileRoutes = require('./routes/profileRoutes')
let articleRoutes = require('./routes/articleRoutes')
let commentRoutes = require('./routes/commentRoutes')
let settingRoutes = require('./routes/settingsRoutes')
let {checkUser} = require('./middleware/authMiddleware')
let cookieParser = require('cookie-parser')


app.listen(3000)
app.set('view engine', 'ejs')
app.use(express.static('public'))
app.use(express.json())
app.use(cookieParser())

app.use("*", checkUser)
app.use(indexRoutes)
app.use(authRoutes)
app.use(articleRoutes)
app.use(profileRoutes)
app.use(commentRoutes)
app.use(settingRoutes)